spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      host: localhost
      port: 27017
      database: testdb

grpc:
  port: 9090
  enable-reflection: true